name: testing-tests
run-name: ${{ github.actor }} is learning how to run tests via CI
on: [ push ]
jobs:

  Everything:
    runs-on: ubuntu-22.04
    container: python:3.11.0
    steps:
      - uses: actions/checkout@v3
      - run: python run.py --install
      - run: python run.py --doctest tests/main.py